### PR TITLE
Fixes version string in HTML metadata.

### LINKED ISSUE #132: Generator version doesn't appear in generated HTML metadata.

### PR DESCRIPTION
**Pull request by Idorobots**
Fixes #132

### CODE REVIEW

File: lambda-blog/src/lambda_blog/utils.clj [hunk 1]
```diff
@@ -100,3 +102,14 @@
                        str
                        subs
                        keyword)))
+
+(defn get-version
+  "Returns current lambda-blog version as specified in Maven pom.properties."
+  []
+  (or (System/getProperty "lambda-blog.version")
+      (let [p (Properties.)]
+        (->> "META-INF/maven/lambda-blog/lambda-blog/pom.properties"
```
Comment (Idorobots) [inline lambda-blog/src/lambda_blog/utils.clj]: Shamefur dispray. :-1:
